import { exec, execFile } from "child_process";
import { existsSync, promises as fs } from "fs";
import path from "path";
import { rimraf } from "rimraf";
import { registrySchema } from "shadcn/schema";

import { registry as pureUIRegistry } from "@/registry/pure-ui/registry";

async function buildRegistryIndex() {
  let index = `/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, Record<string, any>> = {`;

  // Validate the registry schema.
  const parseResult = registrySchema.safeParse(pureUIRegistry);
  if (!parseResult.success) {
    console.error(`❌ Registry validation failed for Pure UI:`);
    console.error(parseResult.error.format());
    throw new Error(`Invalid registry schema for Pure UI`);
  }

  const registry = parseResult.data;

  for (const item of registry.items) {
    const files =
      item.files?.map((file) => ({
        path: typeof file === "string" ? file : file.path,
        type: typeof file === "string" ? item.type : file.type,
        target: typeof file === "string" ? undefined : file.target,
      })) ?? [];

    if (files.length === 0) {
      continue;
    }

    const componentPath = item.files?.[0]?.path
      ? `@/registry/pure-ui/${item.files[0].path}`
      : "";

    index += `
    "${item.name}": {
      name: "${item.name}",
      description: "${item.description ?? ""}",
      type: "${item.type}",
      registryDependencies: ${JSON.stringify(item.registryDependencies)},
      files: [${files.map((file) => {
        const filePath = `registry/pure-ui/${file.path}`;
        return `{
        path: "${filePath}",
        type: "${file.type}",
        target: "${file.target ?? ""}"
      }`;
      })}],
      component: ${
        componentPath
          ? `React.lazy(async () => {
        const mod = await import("${componentPath}")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
        return { default: mod.default || mod[exportName] }
      })`
          : "null"
      },
      categories: ${JSON.stringify(item.categories)},
      meta: ${JSON.stringify(item.meta)},
    },`;
  }

  index += `
  }`;

  console.log(
    `#️⃣  Built Pure UI index with ${
      Object.keys(pureUIRegistry.items).length
    } components`
  );

  // Write unified index.
  const outputPath = path.join(
    process.cwd(),
    "src/registry/pure-ui/__index__.tsx"
  );

  await rimraf(outputPath);
  await fs.writeFile(outputPath, index);
}

async function buildRegistryJsonFile() {
  // 1. Validate the registry schema.
  const parseResult = registrySchema.safeParse(pureUIRegistry);
  if (!parseResult.success) {
    console.error(`❌ Registry validation failed for Pure UI:`);
    console.error(parseResult.error.format());
    throw new Error(`Invalid registry schema for Pure UI`);
  }

  const registry = parseResult.data;

  // 2. Fix the path for registry items.
  const fixedRegistry = {
    ...registry,
    items: registry.items.map((item) => {
      const files = item.files?.map((file) => {
        return {
          ...file,
          path: `src/registry/pure-ui/${file.path}`,
        };
      });

      return {
        ...item,
        files,
      };
    }),
  };

  // 3. Create the output directory and write registry.json.
  const outputDir = path.join(process.cwd());
  await fs.mkdir(outputDir, { recursive: true });

  // 4. Write registry.json to output directory and format it.
  const registryJsonPath = path.join(outputDir, "registry.json");
  await fs.writeFile(registryJsonPath, JSON.stringify(fixedRegistry, null, 2));
  // await new Promise<void>((resolve, reject) => {
  //   execFile("prettier", ["--write", registryJsonPath], (error) => {
  //     if (error) {
  //       reject(error);
  //     } else {
  //       resolve();
  //     }
  //   });
  // });

  // 5. Write temporary registry file needed by shadcn build.
  // const tempRegistryPath = path.join(
  //   process.cwd(),
  //   `src/registry/pure-ui.json`
  // );
  // await fs.writeFile(tempRegistryPath, JSON.stringify(fixedRegistry, null, 2));
}

try {
  console.log("🗂️ Building src/registry/pure-ui/__index__.tsx...");
  await buildRegistryIndex();
  console.log("💅 Building registry.json...");
  await buildRegistryJsonFile();
  console.log("✅ Done");
} catch (error) {
  console.error(error);
}
